{% set name = "loguru" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3138bfdee5f57481a2a6e078714be20f8c71ab1ff3f07f8fb1cfa25191fed2a

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - colorama >=0.3.4  # [win]
    - python >=3.5
    - win32_setctime >=1.0.0  # [win]

test:
  imports:
    - loguru

about:
  home: https://github.com/Delgan/loguru
  license: MIT
  license_family: MIT
  # Package does not ship its license presently
  # license_file: LICENSE
  summary: Python logging made (stupidly) simple
  dev_url: https://github.com/Delgan/loguru

extra:
  recipe-maintainers:
    - mariusvniekerk
